[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.devnet]
etf_defi = "99r9oxGjw29EvJBKEyQreaM8Hj45pP5La2URP1swANCJ"
vault = "FsoSA6MxmuQ6yz9ZJ9EqmizYLZq8KoVWnoudpv1Yww8u"
marinade_strategy = "Eud9MdyGy8HdBzfv6kjKio1uagRWdn69821ajBs7DeqK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --exclude 'tests/helpers/**' 'tests/**/*.ts'"
initialize-mock-oracle = "ts-node scripts/initialize-mock-oracle.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"  # Pyth Program

[[test.validator.clone]]
address = "HovQMDrbAgAYPCmHVSrezcSmkMtXSSUsLDFANExrZh2J"  # BTC/USD Price Feed

[[test.validator.clone]]
address = "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB"  # ETH/USD Price Feed

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"  # SOL/USD Price Feed
