[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.devnet]
etf_defi = "99r9oxGjw29EvJBKEyQreaM8Hj45pP5La2URP1swANCJ"
vault = "AUXhyMXmb4Gwnspmtj6X97saUT2MDJAPVjKnBcipwhz2"
marinade_strategy = "H1Z8qhsV7SLPkmB8g3RtQ5yunzTiHQCCQyS9Sh5SPLpn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --exclude 'tests/helpers/**' 'tests/**/*.ts'"
